### ISSUE TITLE
:setScale doesn't work

### ISSUE THREAD

**Issue by Oxey405** [Whitebrim/AnimatedSprite#14]
Hello ! It looks like the `:setScale` method isn't working on AnimatedSprite. Is that a playdate limitation or just something that's missing ?
Thanks for making this library I look forward for more information !

**Comment by Whitebrim** [comment]
Thanks for the question, @Oxey405
In AnimatedSprite setImage(image, [flip, [scale, [yscale]]]) (https://sdk.play.date/2.1.1/Inside%20Playdate.html#m-graphics.sprite.setImage) is used, so scale is overwritten.
You can change scale only to the entire state - [wiki](https://github.com/Whitebrim/AnimatedSprite/wiki/Config-parameters#xscale-yscale-number-optional). Or the entire animation, if you'll change the scale in default state before creating other states: [wiki](https://github.com/Whitebrim/AnimatedSprite/wiki/Examples#example_3a).
Now I think that this is not an ideal approach if developer wants to change scale for one frame.
Tell me if you need different approach, I'll help you.

**Comment by Oxey405** [comment]
> Thanks for the question, @Oxey405
> In AnimatedSprite setImage(image, [flip, [scale, [yscale]]]) (https://sdk.play.date/2.1.1/Inside%20Playdate.html#m-graphics.sprite.setImage) is used, so scale is overwritten.
> You can change scale only to the entire state - [wiki](https://github.com/Whitebrim/AnimatedSprite/wiki/Config-parameters#xscale-yscale-number-optional). Or the entire animation, if you'll change the scale in default state before creating other states: [wiki](https://github.com/Whitebrim/AnimatedSprite/wiki/Examples#example_3a).
> Now I think that this is not an ideal approach if developer wants to change scale for one frame.
> Tell me if you need different approach, I'll help you.

Thanks! My bad then I searched in the wiki but found nothing...
