### ISSUE TITLE
drawTiled() compatibility?

### ISSUE THREAD

**Issue by LukeSanderson18** [Whitebrim/AnimatedSprite#15]
Seeubg that the default way to add images is through an imagetable, is there a way to add images as drawTiled images instead?

**Comment by LukeSanderson18** [comment]
Disregard - you can use 'playdate.graphics.imagetable.new(count)' to manually add images.

**Comment by Whitebrim** [comment]
> Seeubg that the default way to add images is through an imagetable, is there a way to add images as drawTiled images instead?

You mean this https://sdk.play.date/2.2.0/Inside%20Playdate.html#m-graphics.image.drawTiled ?
This library is all about swapping images from imagetable...

**Comment by Whitebrim** [comment]
This issue is inactive
