### ISSUE TITLE
Extend AnimatedSprite Class?

### ISSUE THREAD

**Issue by Schyzophrenic** [Whitebrim/AnimatedSprite#3]
This may be more a question rather than a bug report. 
I like to have my sprites in a separate class for each. I nonetheless couldn't manage to extend this class, is there a good way to do it? 
Thank you

**Comment by Whitebrim** [comment]
> This may be more a question rather than a bug report. 
> I like to have my sprites in a separate class for each. I nonetheless couldn't manage to extend this class, is there a good way to do it? 
> Thank you

Here's my class for generic enemies, Enemy.lua:

```lua
import 'libraries/AnimatedSprite/AnimatedSprite.lua' 
  
 class("Enemy").extends(AnimatedSprite) 

 function Enemy:init(speed, imagetable, states, animate) 
     Enemy.super.init(self, imagetable, states, animate) 
         self.alive = true 
     self.speed = speed 
         self:setCenter(0, 0) 
         self:moveTo(400, 150) 
 end 
  
 function Enemy:update() 
     if (not self.alive) then 
         return 
     end 
     local newX = self.x - self.speed 
     if newX < -170 then 
         self:remove() 
     end 
     self:moveTo(newX, self.y) 
     self:updateAnimation() -- UPDATE ANIMATION
 end
```

New fugu enemy is created using this line:

`Enemy(gameSpeed, fuguImages, fuguStates, true)`

**Comment by Schyzophrenic** [comment]
Oh thanks, of course! I was not passing all the parameters, silly me! 
Thank you for your help!
