### ISSUE TITLE
Initialize directly with path?

### ISSUE THREAD

**Issue by ebeneliason** [Whitebrim/AnimatedSprite#9]
I'm curious as to why the initializer takes an `imagetable` instead the the path string itself. Is there a common use case for keeping a reference to the `imagetable` outside the sprite? As it stands, it feels like one unnecessary line of setup code.

To avoid a breaking API change, you could do something like:
```
if type(imagetableOrPath) == "string" then
  self.imagetable = gfx.imagetable.new(imagetableOrPath)
else
  self.imagetable = imagetableOrPath
end
```

**Comment by Whitebrim** [comment]
It's crucial optimisation part. If you have several enemies with the same imagetable, you don't need to load it every time for new enemy to spawn.

**Comment by ebeneliason** [comment]
Ah, that makes a lot of sense, thanks. I have a lot of one-off sprites so I hadn't even considered that.

With that said, I suppose you _could_ still support the feature as described above, and recommend in the docs that one provide an `imagetable` for performance reasons when planning to creating many instances of a sprite.

**Comment by Whitebrim** [comment]
c509f473d7584ce84243094baeb251c7d0d37e2d + Edited wiki
